version: "3"

networks:
  qbft-network:
    driver: bridge

services:
  qbft-1:
    container_name:
      qbft-1
    image: hyperledger/besu:latest
    ports:
      - 30401:30401
      - 8601:8601
      - 8602:8602
    environment:
      - BESU_CONFIG_FILE=/var/lib/besu/nodes/qbft-1/configs/config.toml
    volumes:
      - /home/ubuntu/environment/besu-qbft-network/:/var/lib/besu
    networks:
      - qbft-network

  qbft-2:
    depends_on:
      - qbft-1
    container_name:
      qbft-2
    image: hyperledger/besu:latest
    ports:
      - 30403:30403
      - 8603:8603
      - 8604:8604
    environment:
      - BESU_CONFIG_FILE=/var/lib/besu/nodes/qbft-2/configs/config.toml
    volumes:
      - /home/ubuntu/environment/besu-qbft-network/:/var/lib/besu
    networks:
      - qbft-network

  qbft-3:
    depends_on:
      - qbft-2
    container_name:
      qbft-3
    image: hyperledger/besu:latest
    ports:
      - 30405:30405
      - 8605:8605
      - 8606:8606
    environment:
      - BESU_CONFIG_FILE=/var/lib/besu/nodes/qbft-3/configs/config.toml
    volumes:
      - /home/ubuntu/environment/besu-qbft-network/:/var/lib/besu
    networks:
      - qbft-network

  qbft-4:
    depends_on:
      - qbft-3
    container_name:
      qbft-4
    image: hyperledger/besu:latest
    ports:
      - 30407:30407
      - 8607:8607
      - 8608:8608
    environment:
      - BESU_CONFIG_FILE=/var/lib/besu/nodes/qbft-4/configs/config.toml
    volumes:
      - /home/ubuntu/environment/besu-qbft-network/:/var/lib/besu
    networks:
      - qbft-network

  qbft-5:
    depends_on:
      - qbft-4
    container_name:
      qbft-5
    image: hyperledger/besu:latest
    ports:
      - 30409:30409
      - 8609:8609
      - 8610:8610
    environment:
      - BESU_CONFIG_FILE=/var/lib/besu/nodes/qbft-5/configs/config.toml
    volumes:
      - /home/ubuntu/environment/besu-qbft-network/:/var/lib/besu
    networks:
      - qbft-network

  qbft-6:
    depends_on:
      - qbft-5
    container_name:
      qbft-6
    image: hyperledger/besu:latest
    ports:
      - 30411:30411
      - 8611:8611
      - 8612:8612
    environment:
      - BESU_CONFIG_FILE=/var/lib/besu/nodes/qbft-6/configs/config.toml
    volumes:
      - /home/ubuntu/environment/besu-qbft-network/:/var/lib/besu
    networks:
      - qbft-network
      